VERSION: 2
MODEL:
  META_ARCHITECTURE: "GRConvNet" # "GGCNN2"
INPUT:
  MODALITIES: ['depth']
  FORMAT: [PGM]
  MIN_SIZE_TRAIN: (320,)
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 320
  ZOOM: False
  ROTATE: False
  RANDOM_FLIP: "none"
DATALOADER:
  NUM_WORKERS: 10
  ASPECT_RATIO_GROUPING: True
TEST:
  EVAL_PERIOD: 100000
