DATALOADER:
  NUM_WORKERS: 10
DATASETS:
  TEST:
  - graspnet_test
  TRAIN:
  - graspnet_train
INPUT:
  FORMAT:
  - PGM
  MAX_SIZE_TEST: 320
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TEST: 320
  MIN_SIZE_TRAIN:
  - 320
  MODALITIES:
  - depth
  RANDOM_FLIP: none
  ROTATE: true
  ZOOM: false
MODEL:
  GRASP_NET:
    GRCONVNET:
      DROPOUT_RATE: 0.2
    MASK_LOSS: true
    UNCERTAIN_NET: GRConvNet
  META_ARCHITECTURE: UncertainGraspNet
  PIXEL_MEANS:
  - - 0
  PIXEL_STDS:
  - - 1
SOLVER:
  BASE_LR: 0.02
  MAX_ITER: 110000
  STEPS:
  - 50000
  - 80000
  WARMUP_FACTOR: 1.0e-05
  WARMUP_ITERS: 15000
TEST:
  EVAL_PERIOD: 500000